# A github workflow that validates all json files against their schema
name: Validate
on: [push, pull_request]

env:
  TERM: xterm-256color

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Validate json files
      run: npm run validate
