# A github workflow that validates all json files against their schema
name: Validate
on: [push, pull_request]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run jsonschema validation
      run: |
        for file in $(find ./registry -name '*.json'); do
          check-jsonschema --schemafile ./registry/registry.schema.json $file
        done
