# A github workflow that validates all json files against their schema
name: Validate
on: [push, pull_request]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Run jsonschema validation
      run: |
        for file in $(find ./registry -name '*.json'); do
          check-jsonschema --schemafile ./schema/registry.schema.json $file
        done
